### ISSUE TITLE
Error on Build after adding nativescript-auth0 plugin to project

### ISSUE THREAD

**Issue by bbenson36** [sitefinitysteve/nativescript-auth0#14]
```
platforms\android\build\intermediates\res\merged\F0F1\debug\values-v24\values-v24.xml:4: AAPT: 
Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
```

To reproduce:
1. create new nativescript project using
`tns create TestProject --ng`
 2. run project to see that it's working
`cd TestProject`
`tns run android`
3. kill process and install nativescript-auth0
`tns tns plugin add nativescript-auth0`
4. follow instructions to add activities to `AndroidManifest.xml`
5. run project again to see error:
`tns run android`

**Comment by sitefinitysteve** [comment]
Hey man, i am too unfamiliar with angular to even have a clue here.

 Could you cross post to the forums?



On Apr 26, 2017 5:14 PM, "willy3615" <notifications@github.com> wrote:

platforms\android\build\intermediates\res\merged\F0F1\
debug\values-v24\values-v24.xml:4: AAPT: Error retrieving parent for item:
No resource found that matches the given name 'android:TextAppearance.
Material.Widget.Button.Colored'.

To reproduce:

   1. create new nativescript project using
   tns create TestProject --ng
   2. run project to see that it's working
   cd TestProject
   tns run android
   3. kill process and install nativescript-auth0
   tns tns plugin add nativescript-auth0
   4. follow instructions to add activities to AndroidManifest.xml
   5. run project again to see error:
   tns run android

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sitefinitysteve/nativescript-auth0/issues/14>, or mute
the thread

**Comment by bbenson36** [comment]
The issue was my sdk version in my avd and sdk version were different. My avd was using version 23 and sdk version 25. I updated my virtual device to use 25 and that fixed it.

Hopefully this comment will save someone else some grief.
