### ISSUE TITLE
Custom login via username/password rather than hosted web page

### ISSUE THREAD

**Issue by ClaytonBrawley** [sitefinitysteve/nativescript-auth0#43]
Currently, on the iOS application, not only do we have to use a browser-based hosted web page that makes us route away from our application to a login screen that doesn't have a native feel, but iOS also makes us accept a warning notification before being directed to the hosted login page ("<app>" Wants to Use "auth0.com" to Sign In [Cancel/Continue]). 

Is there some way to use a custom login where we pass through user-entered username and password to Auth0 without being directed away from the application? Or at least get rid of the iOS message making us hit "Continue" before being asked to login in the browser.

**Comment by charsleysa** [comment]
@ClaytonBrawley currently this library doesn't expose username/email and password login as it only works for database logins.

Embedded native logins have limitations placed on them by Auth0 (such as no social login support) and so web-based authentication is recommended.

As for the confirmation popup, this is an iOS "feature" imposed by iOS itself and can't be turned off as far as I know. If you are on a paid plan with Auth0 you are able to change the domain shown in the popup. 

To change the domain shown in the popup you must setup a custom domain in the Auth0 dashboard and update all your URIs to use the new custom domain instead of the Auth0 provided domain. 

If you have a requirement to have embedded native login and accept the limitations I can expose some more of the SDK to allow for this, but I would recommend having a chat with Auth0 before making a final decision.

**Comment by ClaytonBrawley** [comment]
It seems that all of the Auth0 username/email and password logins are either deprecated or considered legacy, but if it's possible to be able to login from a custom UI using just username and password that could be very useful. 

I noticed, although I have no experience with it, that even the Auth0-supported React Native library only allows for the browser-based authentication, in case that's in any way relevant.

**Comment by charsleysa** [comment]
@ClaytonBrawley the APIs are deprecated / considered legacy due to security. The username and password login even has limitations on which features you're able to use.

My recommendation would be to stick with the web based authentication and customize the web UI to match your website / app. 

If you still want to go ahead with native login I'll try to schedule in the work sometime this week but I can't provide any guarantees on when it'll be complete.

**Comment by ClaytonBrawley** [comment]
@charsleysa Don't worry about it. It's nice to know I'm using the most secure, feature-rich version of Auth0, even if it's browser-based. I just wanted to make sure I wasn't missing anything. I appreciate your diligence.
