### ISSUE TITLE
Android - Parameter 'prompt' set to 'none' - callback URL issue

### ISSUE THREAD

**Issue by jawa-the-hutt** [sitefinitysteve/nativescript-auth0#61]
### Which platform(s) does your issue occur on?
Android API 28 is all I've tested it on.

### Please, provide the following version numbers that your issue occurs with:
- CLI: 6.0.3 AND 5.4.2
- Cross-platform modules: 6.0.1 AND 5.4.2
- Runtime(s): 6.0.x AND 5.4.x
- Plugin(s): 3.0.1 AND 2.1.1

### Please, tell us how to recreate the issue in as much detail as possible. 
When using Android and we add the `prompt` parameter to the `webAuthencation` initializer and set it to `none`, then we get an error with the callback URL.  here is a screenshot from the Android Emulator.  To be clear, this issue happens on a device as well.

<img width="319" alt="Screen Shot 2019-08-28 at 12 42 45 PM" src="https://user-images.githubusercontent.com/1318561/63879492-714fb200-c991-11e9-9033-60999ff8fa54.png">

This is happening in our source app, so I cloned a copy of the repo and the demo app behaves in the same way.  This issue occurs regardless of whether or not you have logged in before and your credentials have been cached.  Upon first running the app for the first time, the issue will occur and if you have logged in before, then the next time you go through the login process, then it will occur.

### Is there any code involved? 
 In the `demo` folder, add the `prompt` parameters to the `webAuthentication` method in `main-view-model.ts` file and set it to `none`:

```
    this.auth0.webAuthentication({
        scope: 'openid offline_access',
        parameters: {
            prompt: 'none'
        }
    }).then((result) => {
        this.message = JSON.stringify(result);
        console.log(result);
    }).catch((e: Error) => console.log(e, e.stack));
```

**Comment by charsleysa** [comment]
Hi @jawa-the-hutt 

Can you please test this with your source app using a url with the scheme set to your app id instead of https? (e.g. `com.yourapp.auth0://yourtenant.auth0.com/android/com.yourapp.auth0/callback`)

I know there can be some issues on android when using https based urls where the system doesn't send the user back to the app.

**Comment by krthush** [comment]
I'll follow up on this and say that I have exactly the same issue with an S8+ on Android 6.0.0.

I didn't have time to properly investigate/fix it and for my purposes it was okay to avoid this situation and just use "prompt" : "login". I quickly tried what you suggested @charsleysa and I still got the same "Cannot GET etc."

It would be nice though if this were working since using the webAuthentication is probably best way of maintaining the user's access token.

**Comment by charsleysa** [comment]
Hi @krthush 

Just to note, the best way to maintain the user's access token is to use a refresh token unless your needs require something else. The authentication method used by this library is [Auth Code flow with PKCE](https://auth0.com/docs/flows/concepts/auth-code-pkce). Then you can use the securely stored refresh token to request new access tokens.
(Note: the developer is responsible for securely storing the refresh token.)

As for your issue with `prompt: "none"`, can you please post (or private DM) your Auth0 configuration from your Android Manifest file and the code you use to call the webAuthentication + any other configuration code related to Auth0?

**Comment by krthush** [comment]
@charsleysa Ah thanks, okay I'll use the renewCredentials(refreshToken) method whenever I need user info, and find a way of securely storing the refreshToken. Side note question: so it would be bad practice to store the access token? And what would a good method of storing the refresh token in a nativescript app, I would like the user to not have to keep relogging everytime they open/close the app so I can't just store it in a local variable in the app.

To address the `prompt: "none"` issue, here are the following files...

Android Manifest Auth0 config:

![image](https://user-images.githubusercontent.com/33790334/66747228-ed3b8600-ee7b-11e9-853d-393bcb3050d6.png)

webAuthentication code:

![image](https://user-images.githubusercontent.com/33790334/66747199-dbf27980-ee7b-11e9-8d88-b732bc7bf2c0.png)

With the following callback URLs...

`https://emitapp.auth0.com/android/com.emit.app/callback, com.emit.app://emitapp.auth0.com/android/com.emit.app/callback`

**Comment by charsleysa** [comment]
Hi

In our organization we use the nativescript secure storage plugin to securely store the refresh token https://github.com/eddyverbruggen/nativescript-secure-storage

As for the access token, it is advised that you do not store the access token as it can't be revoked (and is generally short lived anyway) and instead just keep it in memory. 

If you could please try the following change and see if it helps you with the prompt none issue:
1) change your Android Manifest config so that the scheme is `com.emit.app`
2) add the scheme property to the input of webAuthentication with the same value

**Comment by krthush** [comment]
Awesome, I'll defo look into that storage plugin - thanks so much 😄 !

I thought my scheme was already `com.emit.app` (maybe my mistake, I uploaded the wrong image at first). Ah great! I changed my code to this...

![image](https://user-images.githubusercontent.com/33790334/66747986-e4e44a80-ee7d-11e9-8484-af11786b19a8.png)

Now seems to be working perfectly 🚀 

Thanks again for the help, and giving us this awesome auth0 plugin ^^

**Comment by charsleysa** [comment]
Awesome! Good to hear that you've got it working!
I'll leave this issue open for @jawa-the-hutt to see if this will help them.

**Comment by jawa-the-hutt** [comment]
@charsleysa and @krthush

This worked.  Thanks!
